In [2]:
import numpy as np
import torch

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
print(x_data)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9084, 0.8020],
        [0.5976, 0.5336]]) 



In [9]:
shape=(2,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4200, 0.4101, 0.8837, 0.6015],
        [0.5575, 0.8446, 0.7542, 0.7419]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
if torch.cuda.is_available():
  rand_tensor = rand_tensor.to('cuda')
print(f"Device tensor is stored on: {rand_tensor.device}")

Device tensor is stored on: cuda:0


In [12]:
rand_tensor[:1]=0
print(rand_tensor)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.5575, 0.8446, 0.7542, 0.7419]], device='cuda:0')


In [22]:
cat = torch.cat([rand_tensor,rand_tensor],dim=1)
print(cat)
cpu_cat = cat.to('cpu')
print(cpu_cat.device)
print(cat.device)

stacked = torch.stack([rand_tensor,rand_tensor],dim=1)
print(stacked)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5575, 0.8446, 0.7542, 0.7419, 0.5575, 0.8446, 0.7542, 0.7419]],
       device='cuda:0')
cpu
cuda:0
tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.5575, 0.8446, 0.7542, 0.7419],
         [0.5575, 0.8446, 0.7542, 0.7419]]], device='cuda:0')


In [30]:
nparray = cpu_cat.numpy()
print(nparray)
print(cpu_cat.add_(1))
print(nparray)
np.add(nparray,1,out=nparray)

[[6.        6.        6.        6.        6.        6.        6.
  6.       ]
 [6.557539  6.8446383 6.7542253 6.7419267 6.557539  6.8446383 6.7542253
  6.7419267]]
tensor([[7.0000, 7.0000, 7.0000, 7.0000, 7.0000, 7.0000, 7.0000, 7.0000],
        [7.5575, 7.8446, 7.7542, 7.7419, 7.5575, 7.8446, 7.7542, 7.7419]])
[[7.        7.        7.        7.        7.        7.        7.
  7.       ]
 [7.557539  7.8446383 7.7542253 7.7419267 7.557539  7.8446383 7.7542253
  7.7419267]]


array([[8.      , 8.      , 8.      , 8.      , 8.      , 8.      ,
        8.      , 8.      ],
       [8.557539, 8.844639, 8.754225, 8.741926, 8.557539, 8.844639,
        8.754225, 8.741926]], dtype=float32)