In [28]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
model = model.to('cuda')
data = torch.rand(1, 3, 64, 64).to('cuda')
labels = torch.rand(1, 1000).to('cuda')

In [29]:
prediction = model(data)

In [30]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [31]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [32]:
optim.step()

In [36]:
a = torch.tensor([2., 3.], requires_grad=True,device='cuda:0')
b = torch.tensor([6., 4.], requires_grad=True,device='cuda:0')

Q = 3*a**3 - b**2
print(Q)

external_grad = torch.tensor([1., 1.]).to('cuda')
Q.backward(gradient=external_grad)

tensor([-12.,  65.], device='cuda:0', grad_fn=<SubBackward0>)


In [50]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True], device='cuda:0')
tensor([True, True], device='cuda:0')


In [51]:

from torch import nn, optim
model = torchvision.models.resnet18(pretrained=True)
# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Linear(512, 10)
# Optimize only the classifier
optimizer = optim.SGD(model.fc.parameters(), lr=1e-2, momentum=0.9)